[hu]
languageName = "Magyar"
languagedirection = "ltr"
title = "Andris webszelete"
params.sidebar.subtitle = "Ennek a bizonyos Papp Andrisnak van egy rossz szokása hónapokig eltűnni és nem adni életjelet. Na, ez a blog ezt hivatott kiküszöbölni."
#menu.main.name = "Asd"
weight = 1

[ja]
languageName = "日本語"
languagedirection = "ltr"
title = "パップ・アンドラーシュ"
params.sidebar.subtitle = "東北大で研究留学生。興味はロボット工学、CV"
weight = 2