[hu]
languageName = "Magyar"
languagedirection = "ltr"
title = "Andris webszelete"
params.sidebar.subtitle = "Ennek a bizonyos Papp Andrisnak van egy rossz szokása hónapokig eltűnni és nem adni életjelet. Na, ez a blog ezt hivatott kiküszöbölni."
weight = 1

[ja]
languageName = "日本語"
languagedirection = "ltr"
title = "パップ・アンドラーシュ"
params.sidebar.subtitle = "東北大で研究留学生。ハンガリー・ブダペスト生まれ育ち。興味はロボット工学、CV、グラフィックス。市電に熱中。"
weight = 2

[en]
languageName = "English"
languagedirection = "ltr"
title = "András D. Papp"
params.sidebar.subtitle = "Research student at Tohoku University, born and raised in Budapest, Hungary. Interests include robotics, computer vision and CG. Tram enthusiast."
weight = 3
