# Configure main menu and social menu
# [[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# [main.params]
# icon = "home"
# newtab = true

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/anderudp"
weight = 1

[social.params]
icon = "icons8-facebookv3"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/anderudp"
weight = 2

[social.params]
icon = "icons8-githubv2"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/anderudp/"
weight = 3

[social.params]
icon = "icons8-linkedinv2"

# [[social]]
# identifier = "wantedly"
# name = "Wantedly"
# url = "https://www.linkedin.com/in/anderudp/"
# weight = 4

# [social.params]
# icon = "images"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/anderudp/"
weight = 5

[social.params]
icon = "icons8-instagram"
